name: "Shared steps"
runs:
  using: "composite"
  steps:
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.SWIFT_PROFILE_SSH_KEY }}
            ${{ secrets.SLIP_10_SSH_KEY }}
            ${{ secrets.MNEMONIC_SSH_KEY }}
            ${{ secrets.SWIFT_ENGINE_TOOLKIT_SSH_KEY }}
            ${{ secrets.CONVERSE_SSH_KEY }}
            ${{ secrets.BITE_SSH_KEY }}
            ${{ secrets.FASTLANE_MATCH_REPO_SSH_KEY }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.1"

      - name: "Set up ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
