import Foundation

extension PersonaFieldValue.PostalAddress {
	/// The research house found that the top destination for crypto adoption is (in order):
	/// Australia,
	/// US
	/// Brazil,
	/// United Arab Emirates (UAE),
	/// Hong Kong
	/// Taiwan
	/// India,
	/// Canada
	/// Turkey
	/// Singapore
	public enum Country: String, Sendable, Hashable, Codable {
		case afghanistan
		case argentina
		case angola
		case algeria
		case albania
		case andorra
		case armenia
		case australia
		case austria
		case azerbaijan
		case bangladesh
		case belarus
		case belgium
		case bolivia
		case bosniaAndHerzegovinia
		case bulgaria
		case brazil
		case bruneiDarussalam
		case canada
		case cameroon
		case chile
		case china
		case colombia
		case croatia
		case cyprus
		case czechRepublic
		case democraticRepublicOfTheCongo
		case denmark
		case ecuador
		case egypt
		case estonia
		case ethiopia
		case finland
		case france
		case frenchGuiana
		case georgia
		case germany
		case ghana
		case greece
		case guyana
		case hongKong
		case hungary
		case iceland
		case india
		case iran
		case iraq
		case ireland
		case italy
		case ivoryCoast; public static let côteDIvoire: Self = .ivoryCoast
		case indonesia
		case japan
		case kazakhstan
		case kenya
		case kuwait
		case latvia
		case liechtenstein
		case lithuania
		case luxembourg
		case macao
		case madagascar
		case malaysia
		case malta
		case mexico
		case moldova
		case monaco
		case mozambique
		case montenegro
		case morocco
		case myanmar
		case nepal
		case netherlands
		case newZealand
		case niger
		case nigeria
		case northKorea
		case northMacedonia
		case norway
		case papuaNewGuinea
		case pakistan
		case paraguay
		case peru
		case philippines
		case poland
		case qatar
		case romania
		case russia
		case saudiArabia
		case sanMarino
		case serbia
		case singapore
		case slovakia
		case slovenia
		case southKorea
		case southAfrica
		case spain
		case sudan
		case suriname
		case sweden
		case switzerland
		case taiwan
		case tanzania
		case thailand
		case turkey
		case vietnam
		case uganda
		case ukraine
		case unitedArabEmirates
		case unitedKingdom
		case unitedStates
		case uruguay
		case uzbekistan
		case vaticanCity
		case venzuela
		case yemen
	}
}
