import Foundation

// MARK: - PersonaData.PostalAddress.Country
extension PersonaData.PostalAddress {
	public enum Country: String, Sendable, Hashable, Codable, CaseIterable, Identifiable {
		case afghanistan
		case argentina
		case angola
		case antiguaAndBarbuda
		case algeria
		case albania
		case andorra
		case armenia
		case aruba
		case australia
		case austria
		case azerbaijan
		case bahrain
		case barbados
		case bangladesh
		case belarus
		case belize
		case belgium
		case benin
		case bolivia
		case bosniaAndHerzegovinia
		case botswana
		case brazil
		case bruneiDarussalam
		case bulgaria
		case burkinaFaso
		case burundi
		case canada
		case cambodia
		case cameroon
		case capeVerde
		case centralAfricanRepublic
		case czechRepublic
		case chad
		case chile
		case china
		case colombia
		case comoros
		case costaRica
		public static let côteDIvoire: Self = .ivoryCoast
		case croatia
		case cuba
		case curacao
		case cyprus

		/// aka "Congo-Kinshasa" aka "DRC" (formerly known as "Zaire")
		case democraticRepublicOfTheCongo

		case denmark
		case djibouti
		case dominicanRepublic
		case dominica
		case ecuador
		case egypt
		case elSalvador
		case eritrea
		case equatorialGuinea
		case estonia
		case ethiopia
		case eswatini
		case finland
		case france
		case frenchGuiana
		case gabon
		case gambia
		case georgia
		case germany
		case ghana
		case greece
		case greenland
		case grenada
		case guatemala
		case guyana
		case guinea
		case guineaBissau
		case haiti
		case honduras
		case hongKong
		case hungary
		case iceland
		case india
		case iran
		case iraq
		case ireland
		case isreal
		case italy
		case ivoryCoast
		case indonesia
		case jamaica
		case japan
		case jordan
		case kazakhstan
		case kenya
		case kuwait
		case laos
		case latvia
		case lebanon
		case lesotho
		case liberia
		case libya
		case liechtenstein
		case lithuania
		case luxembourg
		case macao
		case madagascar
		case malaysia
		case martinique
		case mali
		case malawi
		case malta
		case mauritania
		case mauritius
		case mexico
		case moldova
		case monaco
		case mozambique
		case mongolia
		case montenegro
		case morocco
		case myanmar
		case namibia
		case nepal
		case netherlands
		case newZealand
		case nicaragua
		case niger
		case nigeria
		case northKorea
		case northMacedonia
		case norway
		case oman
		case panama
		case papuaNewGuinea
		case pakistan
		case palestinianTerritories
		case paraguay
		case peru
		case philippines
		case poland
		case puertoRico
		case qatar

		/// aka "Congo-Brazzaville" or simply "Congo"
		case republicOfCongo

		case reunion
		case romania
		case rwanda
		case russia
		case saudiArabia
		case sanMarino
		case senegal
		case serbia
		case seychelles
		case singapore
		case sierraLeone
		case slovakia
		case slovenia
		case somalia
		case southKorea
		case southAfrica
		case southSudan
		case spain
		case sriLanka
		case sudan
		case suriname
		case sweden
		case switzerland
		case taiwan
		case tajikistan
		case tanzania
		case thailand
		case togo
		case trinidadAndTobago
		case tunisia
		case turkey
		case turkmenistan
		case vietnam
		case uganda
		case ukraine
		case unitedArabEmirates
		case unitedKingdom
		case unitedStates
		case uruguay
		case uzbekistan
		case vaticanCity
		case venezuela
		case yemen
		case zambia
		case zimbabwe
	}
}

extension PersonaData.PostalAddress.Country {
	public typealias ID = RawValue
	public var id: ID { rawValue }
}
