fastlane_require 'dotenv'

before_all do
    Dotenv.load ".env.secret"
    ensure_git_status_clean
end

platform :ios do
    before_all do
        Dotenv.load ".env.ios"
    end

    desc "Builds and archives the app"
    lane :build do
        install_distribution_certificate
        build_app
    end

    desc "Runs test"
    lane :tests do
        run_tests
    end

    desc "Builds and deploys beta app to TestFlight"
    lane :beta_deploy do
        install_distribution_certificate
        version = bump_version
        commit_version_bump(xcodeproj: ENV['PROJ_PATH'])
        add_git_tag(tag: version)
        build_app
        api_key = app_store_connect_api_key
        upload_to_testflight(
            api_key: api_key
        )
        push_to_git_remote
    end

    lane :push_to_main_test do
        install_distribution_certificate
        version = bump_version
        commit_version_bump(xcodeproj: ENV['PROJ_PATH'])
        push_to_git_remote(
            branch: "main"
        )
    end

    desc "Installs certificates on the machine"
    lane :install_certificates do
        install_development_certificate
        install_distribution_certificate
    end

    desc "Installs distribution certificate"
    lane :install_distribution_certificate do
        code_signing(type: "appstore")
    end

    desc "Installs development certificate"
    lane :install_development_certificate do
        code_signing(type: "development")
    end

    desc "Generates new certificates if needed"
    lane :generate_new_certificates do
        code_signing(type: "development", readonly: false)
        code_signing(type: "appstore", readonly: false)
    end

    desc "Registers a new iPhone device and updates the certificates"
    lane :register_new_iphone_device do
        register_new_device
        generate_new_certificates
    end

end

platform :mac do
    before_all do
        Dotenv.load ".env.mac"
    end

    desc "Runs tests"
    lane :tests do
        run_tests
    end

    desc "Installs certificates on the machine"
    lane :install_certificates do
        code_signing(type: "development")
    end

    desc "Generates new certificates if needed"
    lane :generate_new_certificates do
        code_signing(type: "development", readonly: false)
    end

    desc "Registers a new mac device and updates the certificates"
    lane :register_new_mac_device do
        register_new_device
        generate_new_certificates
    end
end

desc "Bumps up the patch version"
private_lane :bump_version do
    increment_version_number_in_xcodeproj(
        bump_type: 'patch',
        xcodeproj: ENV['PROJ_PATH'],
        scheme: ENV['SCHEME']
    )

    get_version_number_from_xcodeproj(
        xcodeproj: ENV['PROJ_PATH'],
        scheme: ENV['SCHEME']
    )
end

private_lane :register_new_device do |options|
    name = prompt(text: "Device name: ")
    udid = prompt(text: "Device UDID: ")
    devices = {}
    devices[name] = udid

    app_store_connect_api_key
    register_devices(devices: devices)
end

private_lane :code_signing do |options|
    readonly = options.fetch(:readonly, true)
    type = options.fetch(:type, "development")

    if !readonly
        app_store_connect_api_key
    end

    create_keychain(
        unlock: false,
        timeout: 0
    ) 
    sync_code_signing(
        type: type,
        force_for_new_devices: true,
        readonly: readonly
    )
end
