#!/bin/bash

echo "Installing CLI tools (if missing)"
if ! command -v swiftformat &> /dev/null; then
    brew install swiftformat
fi

DIR=$(cd "$(dirname "$BASH_SOURCE")" && pwd)

pushd "$DIR/.." > /dev/null

echo "Imported Git hooks"
mkdir -p .git/hooks
cp -f "scripts/pre-commit" .git/hooks/
cp -f "scripts/git-format-staged" .git/hooks/

echo "Done ✅"

popd > /dev/null