#!/usr/bin/env bash

echo "Installing CLI tools (if missing)"
if ! command -v realpath &> /dev/null; then
    brew install coreutils
fi
if ! command -v swiftformat &> /dev/null; then
    brew install swiftformat
fi

DIR=$(cd "$(dirname "$BASH_SOURCE")" && pwd)

pushd "$DIR/.." > /dev/null

echo "Symlinking Git hooks"
GIT_HOOKS_DIR=.git/hooks
mkdir -p "$GIT_HOOKS_DIR"
ln -sf "$(realpath --relative-to=.git/hooks scripts)/pre-commit" "$GIT_HOOKS_DIR"

echo "Importing custom Xcode templates"
XCODE_TEMPLATES_DIR="$HOME/Library/Developer/Xcode/Templates/FileTemplates/Custom/"
mkdir -p "$XCODE_TEMPLATES_DIR"
ln -sf "$(realpath --relative-to=$XCODE_TEMPLATES_DIR templates)/TCA.xctemplate" "$XCODE_TEMPLATES_DIR"

echo "Done ✅"

popd > /dev/null