name: CI

on:
  push:
    branches:
      - chore/try-macos-13-xl 

jobs:

  test-and-build:
    name: "Test and build"
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.SWIFT_PROFILE_SSH_KEY }}
            ${{ secrets.SLIP_10_SSH_KEY }}
            ${{ secrets.MNEMONIC_SSH_KEY }}
            ${{ secrets.SWIFT_ENGINE_TOOLKIT_SSH_KEY }}
            ${{ secrets.CONVERSE_SSH_KEY }}
            ${{ secrets.BITE_SSH_KEY }}
            ${{ secrets.FASTLANE_MATCH_REPO_SSH_KEY }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.3.1"

      - name: "Set up ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: "Install additional deps"
        run: |
          echo "${{ secrets.FASTLANE_SECRETS }}" | base64 --decode > fastlane/.env.secret
          brew install xcbeautify

      - name: "Unit tests (debug)"
        run: |
          xcodebuild -scheme "Unit Tests" -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' -skipPackagePluginValidation clean build test
